### PR TITLE
add erlang 19, 20 for test

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by massemanet** [comment]
thanks for the pr.
will have to fix the failures before merge

**Comment by getong** [comment]
```shell
=INFO REPORT==== 29-Aug-2017::07:41:28 ===
    current_function: {prfHost,loop,1}
    line: 119
    lost_target: {killed,{gen_server,call,[prfDog,quit]}}

=INFO REPORT==== 29-Aug-2017::07:41:28 ===
    current_function: {watchdog,mk_send_tcp,4}
    line: 541
    {didnt_make_subscriber,tcp,{badmatch,{error,econnrefused}}}

Pending:
  prfDog:t1_test/0
    %% Unknown error: timeout
  undefined
    %% Unknown error: {blame,[1,1,19,2]}
```
I ran three times, and the first time faild. The other two work.

**Comment by hanssv** [comment]
Fixing `make test` to do `dialyzer` rather than `dialyze` will probably reveal more problems...

**Comment by massemanet** [comment]
typos... they're so amusing :<
alas, dialyzing redbug is doomed since OTP added a bunch of ~~bogus~~ optimistic type annotations to the parser. There ~~might be~~ are probably legit errors, but since I've moved redbug development to http://github.com/massemanet/redbug I'm not going to fix them.

**Pull request merged**
